### PR TITLE
avs3 (IEEE 1857.10) video codec mapping

### PR DESCRIPTION
**Pull request by xatabhk**
Standard document:
1857.10-2021 - IEEE Standard for Third Generation Video Coding (https://standards.ieee.org/standard/1857_10-2021.html)

Encoding tool:
Ffmpeg with avs3 enabled: https://github.com/xatabhk/FFmpeg-avs2-avs3/releases/tag/n4.4-dev-avs3
Command line:

             ffmpeg -i xxxx.mp4 -vcodec avs3 -acodec copy xxxx_avs3.mkv
             ffmpeg -i xxxx.mp4 -vcodec avs3 -acodec copy xxxx_avs3.mkv`

Players:
(1) Ffmpeg with avs3 enabled: (https://github.com/xatabhk/FFmpeg-avs2-avs3/releases/tag/n4.4-dev-avs3):
Command line:

             ffplay xxxx_avs3.mkv
(2) VLC 3.0.x with avs3 enabled: https://github.com/xatabhk/vlc-3.0-avs2-avs3/releases
(3) Mpc-hc 1.9.x with avs3 enabled: https://gitee.com/zhengtianbo/cavs-avs2-avs3_decoder_added_to_mpc_hc/releases

Avs3-MKV samples:
https://github.com/xatabhk/avs2-avs3-video-samples

### CODE REVIEW

**Comment by robUx4** [comment]
Technically new codec should have their own document with more information than just a CodecID, similar to how [AV1](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/codec/av1.md) explains how to map it internal structures to Matroska elements, which are mandatory in which context, etc.

Since AVS2 is already in there it's OK for now. But it's definitely not enough to implement proper support.

Side note: the VLC support could be merged upstream by adding support for [uavs3d](https://github.com/uavs3/uavs3d) in the contribs, enabling the ffmpeg compilation flag and adding the extra patch you have.

**Comment by xatabhk** [comment]
> Side note: the VLC support could be merged upstream by adding support for [uavs3d](https://github.com/uavs3/uavs3d) in the contribs, enabling the ffmpeg compilation flag and adding the extra patch you have.

Yes. You are right. I am indeed using this approach for the VLC support.

**Comment by robUx4** [comment]
@xatabhk we have started integrating [AVS2](https://code.videolan.org/videolan/vlc/-/merge_requests/1187) and [AVS3](https://code.videolan.org/videolan/vlc/-/merge_requests/1188) support in VLC 4.0.

The problem is that we can't integrate the libraries in our contribs, meaning it won't be used in regular builds.

The problem with the AVS2 library might be added as it's GPL licensed and our default builds are GPL ones. Although there are 2 critical issues that are fixed https://github.com/pkuvcl/davs2/commit/b06d7585620f4e90a6d19a2926bb4e59793b8942 and https://github.com/pkuvcl/davs2/commit/cf6ce77c2969ac6f36dd325cede925fa028364aa but are not in proper releases yet. We'd prefer to use a crash-free version. Is there any new release planned since the 1.6 from 2018 ?

The AVS3 on the other won't be used as it's a BSD 4-clause license, meaning it needs an "advertising" in the software with a copyright notice. This is incompatible with GPL code. Would it be possible to relicense the code to a different license like the BSD 3-clause that is [GPL compatible](https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) ?

**Comment by xatabhk** [comment]
>Is there any new release planned since the 1.6 from 2018 ?
> Would it be possible to relicense the code to a different license like the BSD 3-clause that is [GPL compatible]?>>(https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) ?

I cannot answer the 2 questions but I have routed them to the developers of avs2/avs3.

**Comment by robUx4** [comment]
> I cannot answer the 2 questions but I have routed them to the developers of avs2/avs3.

Awesome !

**Comment by hwrenx** [comment]
Hi there, thanks for attention to AVS2 & AVS3 !
A few days ago, uavs3d has updated its license to BSD-3, which is now compatible with GPL code.
As for davs2, there is a new tag 1.7 released to mark the latest and stable version (https://github.com/pkuvcl/davs2/tree/1.7). However, the impact of changing davs2 from GPLv2 to GPL is still being discussed.

**Pull request merged**
