### PR TITLE
Add a separate document that will receive all the Chapter Codecs parts removed

### PR DESCRIPTION
**Pull request by robUx4**
Implements the changes for #467

### CODE REVIEW

**Comment by robUx4** [comment]
There might also be legal issues mentioning the DVD specs/format which is not public or open. In the end it might be a RFC document but something we do on the side.

**Comment by hubblec4** [comment]
LGTM

> There might also be legal issues mentioning the DVD specs/format which is not public or open.

There are many web sites which shows DVD-specs in more details as Matroska does.

**Comment by JeromeMartinez** [comment]
> There are many web sites which shows DVD-specs in more details as Matroska does.

It does not mean that it is legal ;-).
But generally speaking I guess that this is part of fair use.

**Comment by SpencerDawkins** [comment]
Could I ask what the proper reference for DVD format is that you're thinking of?

I'm happy to chase this with ADs and IETF lawyers if that's helpful.

**Review by retokromer — APPROVED** [review]

**Comment by robUx4** [comment]
The DVD specs are found in "DVD Books" https://web.archive.org/web/20100501012533/http://www.mpeg.org/MPEG/DVD/General/Books.html
They must be bought from the [DVD Forum](http://www.dvdforum.org).

**Comment by JeromeMartinez** [comment]
I suggest to merge this PR (technical task) and open an issue for tracking the question about potential legal issue in putting a (very small) part from the DVD spec.

**Pull request merged**
