### PR TITLE
fix UTF-8 that appear in the TXT output

### PR DESCRIPTION
**Pull request by robUx4**
When uploading the XML it warns that some UTF8 chars are found and won't let me upload.
This should fix this warning+error.

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
Not possible to keep the UTF-8 version when not TXT?

**Comment by robUx4** [comment]
I'm sending a version without the UTF-8 to see if it goes through.

**Comment by robUx4** [comment]
It still tells me to fix things...

**Comment by robUx4** [comment]
It went through without, so closing.
Thanks @dericed !

**Pull request closed without merging**
