### PR TITLE
fix UTF-8 that appear in the TXT output

### PR DESCRIPTION
**Pull request by robUx4**
The RFC generator complains some character at UTF-8.

### CODE REVIEW

**Comment by retokromer** [comment]
I am not familiar with the RFC generator, but could `&egrave;` etc. work or is only 7-bit ASCII allowed?

**Comment by mcr** [comment]
Accents are supported on author's name, but not in the general text.
I think that xml2rfc will support &egrave:

**Comment by retokromer** [comment]
Thank you for the information, @mcr

**Comment by robUx4** [comment]
I tried the XML/HTML accent in the author, but idnits doesn't like it. And I found more hidden UTF-8 chars to fix.

**Comment by retokromer** [comment]
Thanks for trying, @robUx4. It seems to be a RFC generator issue we cannot fix here.

**Review by retokromer — APPROVED** [review]

**Pull request merged**
