### PR TITLE
reference FLAC as RFC9639

### PR DESCRIPTION
**Pull request by robUx4**
Draft for now as it won't build until it's officially published. For now it's available at https://www.rfc-editor.org/authors/rfc9639.html

### CODE REVIEW

**Review by retokromer — APPROVED** [review]

**Comment by retokromer** [comment]
RCF 9639 should be published quite soon.

**Comment by ktmf01** [comment]
Perhaps the whole section can be replaced by a reference to section 10.2 of RFC 9639?

**Comment by robUx4** [comment]
> Perhaps the whole section can be replaced by a reference to section 10.2 of RFC 9639?

That would indeed be a lot better.

**Comment by robUx4** [comment]
It will create a nice link to the appropriate section in the HTML version.

**Pull request merged**
