### PR TITLE
Fix EBML signed VINT encoding description

### LINKED ISSUE #726: EBML Lacing details are incorrect
Hello! I'm opening this issue to describe a problem in the specification documentation related to this section: 

https://github.com/ietf-wg-cellar/matroska-specification/blob/bdb0b3c01a13537ad6f60d90ba80cf89ff2360c2/notes.md#ebml-lacing

The documentation states:
> The first frame size is encoded as an EBML Unsigned Integer Element value. The other frame sizes are encoded as a difference with the previous frame size as EBML Signed Integer Element values. That corresponds to an EBML Data Size Values with two’s complement notation with the leftmost bit being the sign bit as found in [@!RFC8794], giving this range of values:

The part I'd like to point out in the above excerpt is that subsequent frame sizes should be encoded as EBML Signed Integer Element values, which use *two's complement notation*.

The document then follows with a table showing an example encoding for a block with frame sizes of 800, 500, and 1000.  The relevant part here is the size of the second frame:

> 7-8 | 0x5E 0xD3 | Size of the second frame (500 - 800 = -300 = - 0x12C + 0x1FFF + 0x4000)

The size expressed as a decimal is definitely "-300".  However, the binary output shown **is not -300 in two's complement notation**, and the formula in parenthesis **does not result in two's complement notation**.  The correct binary for -300 (in two's complement notation using 14 bits, which is the number of usable bits for the value of the vint) is {11 1110 1101 0100}.  Prepending the vint marker {01} for two value bytes gives us: 0x7ED4.

Is there a consensus on how ebml lacing should actually be represented?  If so, it'd be great to update the documentation to reflect that correctly.

Handy calculator for two's complement: https://www.omnicalculator.com/math/twos-complement

### PR DESCRIPTION
**Pull request by robUx4**
Fixes #726

### CODE REVIEW

**Comment by robUx4** [comment]
The bottom range value was actually correct. However the upper boundary seems to allow 1 more value that we used to allow. This is **not** what the code actually does https://github.com/ietf-wg-cellar/matroska-specification/issues/726#issuecomment-1445148868

But encoding 2<sup>6</sup> (64) fits in the 7 bits we have: 2<sup>6</sup> + (2<sup>6</sup>-1) = 127 = `0111 1111`.

**Comment by robUx4** [comment]
That comes down to the libebml code that is not allowing this https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlElement.cpp#L93

It should have been `if (Length > -64 && Length <= 64)`.

So we have to mention that in the text as well. Because libmatroska will not be able to read that `1111 1111` as 64.

**Comment by robUx4** [comment]
Actually it cannot write that value, but it can read the value properly https://github.com/Matroska-Org/libebml/blob/a81936929f9c2c21e0ed0e11476df42a01111eb8/src/EbmlElement.cpp#L189. The size read will be 1 octet and so 63 will be substracted from 127.

This is also the case for libavformat where the substracted value depends on the size read, not the value itself: https://github.com/FFmpeg/FFmpeg/blob/3153c441e1d980ff9931ed26a0e01b4e366ac521/libavformat/matroskadec.c#L3249

So I'd just keep the spec as done here. `libmatroska` could be optimized to write 64 in 1 octet (and that code moved out of libebml for good)

**Review by hubblec4 — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Comment by robUx4** [comment]
Fixed the formula, it's actually 2<sup>(7*n)-2</sup>-1

**Comment by robUx4** [comment]
Merging as the reading code (of libmatroska/libebml) has been verified to be able to read the upper boundaries we were not writing so far.

**Pull request merged**
